version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current-20.04

jobs:
  job1:
    executor: default
    steps:
      - checkout
      - run: echo "This is job is pipeline << pipeline.id >>, job $CIRCLE_JOB"
  job2:
    executor: default
    steps:
      - checkout
      - run: echo "This is job is pipeline << pipeline.id >>, job $CIRCLE_JOB"

workflows:
  version: 2
  w1:
    jobs:
      - job1
