version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current-20.04

commands:
  check-cwd:
    steps:
      - run:
          name: show current working directory
          command: |
            pwd
            ls -la
jobs:
  showinfo:
    executor: default
    parameters:
      title:
        type: string
        default: showinfo
    steps:
      - checkout
      - run: echo "This job [<< parameters.title >>] at << pipeline.id >> $CIRCLE_JOB"
  job_store_cache_in_workflow:
    executor: default
    steps:
      - checkout
      - run:
          name: Generate file
          command: |
            make generate
            make log VALUE=<< pipeline.id >>-<< pipeline.git.branch >>-<< pipeline.schedule.name >>-<< pipeline.trigger_source >>
      - check-cwd
      - save_cache:
          # Branch毎 + 各CIワークフロー毎に生成
          key: store-{{ .Branch }}-{{ .Revision }}
          paths:
            - dist
  job_restore_cache_in_workflow:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: store-{{ .Branch }}-{{ .Revision }}
      - check-cwd
      - run:
          name: check cache file
          command: |
            make check
            make show-log
    
  job_restore_cache_any:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: store-{{ .Branch }}-
      - check-cwd
      - run:
          name: show log
          command: make show-log
  
  job_store_workspace:
    executor: default
    steps:
      - checkout
      - run:
          name: Generate file
          command: |
            make generate
            make log VALUE=<< pipeline.id >>-<< pipeline.git.branch >>-<< pipeline.schedule.name >>-<< pipeline.trigger_source >>
      - check-cwd
      - persist_to_workspace:
          root: .
          paths:
            - dist

  job_restore_workspace:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - check-cwd
      - run:
          name: show log
          command: make show-log


workflows:
  version: 2
  cache-control-in-workflow:
    jobs:
      - showinfo
      - job_store_cache_in_workflow
      - job_restore_cache_in_workflow:
          requires:
            - job_store_cache_in_workflow
  cache-restore-previous-run:
    jobs:
      - job_restore_cache_any
  workspace:
    jobs:
      - job_store_workspace
      - job_restore_workspace:
          requires:
            - job_store_workspace
  approve-only-feature:
    jobs:
      - run-approval:
          type: approval
          filters:
            branches:
              only:
                - /feature\/.*/
      - showinfo:
          requires:
            - run-approval
  approve-ignore-feature:
    jobs:
      - run-approval:
          type: approval
          filters:
            branches:
              ignore:
                - /feature\/.*/
      - showinfo:
          requires:
            - run-approval
  branch-filter-feature:
    jobs:
      - showinfo:
          title: branch-only-feature
          filters:
            branches:
              only:
                - /feature\/.*/
      - showinfo:
          title: branch-ignore-feature
          filters:
            branches:
              ignore:
                - /feature\/.*/
  tag-filter-feature:
    jobs:
      - showinfo:
          title: tag-only-test
          filters:
            tags:
              only:
                - /test\/.*/
            branches:
              ignore: /.*/
      - showinfo:
          title: tag-ignore-test
          filters:
            tags:
              ignore:
                - /test\/.*/
            branches:
              ignore: /.*/
