version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current-20.04

jobs:
  showinfo:
    executor: default
    steps:
      - checkout
      - run: echo "This job is << pipeline.id >> $CIRCLE_JOB"
  job_store_cache:
    executor: default
    steps:
      - checkout
      - run:
          name: Generate file
          command: make generate
      - save_cache:
          key: store-{{ .Branch }}
          paths:
            - dist
  job_restore_cache:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: store-{{ .Branch }}
      - run: ls -la 
      - run:
          name: check cache file
          command: make check

workflows:
  version: 2
  w1:
    jobs:
      - showinfo
      - job_store_cache
      - job_restore_cache:
          requires:
            - job_store_cache
