version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:current-20.04

commands:
  check-cwd:
    steps:
      - run:
          name: show cdw
          command: |
            pwd
            ls -la
jobs:
  showinfo:
    executor: default
    steps:
      - checkout
      - run: echo "This job is << pipeline.id >> $CIRCLE_JOB"
  job_store_cache:
    executor: default
    steps:
      - checkout
      - run:
          name: Generate file
          command: make generate
      - check-cwd
      - save_cache:
          key: store-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - dist
  job_restore_cache:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: store-{{ .Branch }}-{{ .BuildNum }}
      - check-cwd
      - run:
          name: check cache file
          command: make check

workflows:
  version: 2
  cache-control:
    jobs:
      - showinfo
      - job_store_cache
      - job_restore_cache:
          requires:
            - job_store_cache
